# Generated by Django 5.0.7 on 2024-07-19 10:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('catID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('catName', models.CharField(max_length=255)),
                ('catType', models.CharField(choices=[], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('requestID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('requestDate', models.DateField(auto_now_add=True)),
                ('requestReason', models.TextField(blank=True, help_text='Specify the reason for the request')),
                ('requestStatus', models.CharField(choices=[], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('storeID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('storeName', models.CharField(max_length=255)),
                ('layout', models.CharField(choices=[('aisle', 'Aisle'), ('grid', 'Grid'), ('free_flow', 'Free Flow')], max_length=50)),
                ('storeLocation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('work_email', models.EmailField(default=None, max_length=254)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendorID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('vendorName', models.CharField(max_length=255)),
                ('contactPerson', models.CharField(default=None, max_length=255)),
                ('vendorAddress', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(default=None, max_length=13)),
                ('vendorEmail', models.EmailField(default=None, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=255)),
                ('itemUnit', models.CharField(choices=[], max_length=100)),
                ('itemPrice', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(99999.99)])),
                ('minLevel', models.IntegerField(max_length=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('itemCatID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='server.category')),
                ('vendorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='server.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='RequestDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('ExpectedPrice', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='item', to='server.item')),
                ('requestID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='server.request')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='requestUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='server.user'),
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('PurchaseRequestID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('AuthorizedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Approver', to='server.user')),
            ],
        ),
    ]
